### ISSUE TITLE
possible mistake in SU_SL implementation

### ISSUE THREAD

**Issue by rsy56640** [levelfour/SU_Classification#1]
I've read your paper and I was confused with `SU_SL.fit()` ,
In 'su_learning.py' line 59: ` b = 2 * p_s * k_s.T.mean(axis=1) - k_u.T.mean(axis=1)`,
I note the formula should be 
$\frac{\pi_S}{n_S}X_S^T\pmb 1-\frac{1}{n_U}X_U^T\pmb 1$,
The '2' seems like a mistake.

**Comment by levelfour** [comment]
Hi @rsy56640,

I sincerely apologize that I did not notice your message for such a long time...
Regarding your question, I admit this is a quite confusing part and I've got similar questions via email several times: the clutter happens due to the usage of `np.mean`.
`k_s.T.mean(axis=1)` takes the mean over `2 * n_s` entries, while the original paper supposes `k_s.T.sum(axis=1) / n_s` --- there is `2 *` gap between them.

To avoid confusion, I added comments to the corresponding part of the code.
Thank you for the inquiry!
